version: '3.8'

services:
  n8n:
    build: .
    restart: unless-stopped
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password

      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n_password

      - NODE_FUNCTION_ALLOW_EXTERNAL=pg

      # Твой внешний адрес для ссылок вебхуков (ОБЯЗАТЕЛЬНО)
      - WEBHOOK_URL=https://vadym-n8n.up.railway.app/

      # Если стоишь за Nginx/Traefik или любым обратным прокси
      - N8N_PROXY_HOPS=1
      - N8N_PROTOCOL=https
      - N8N_HOST=vadym-n8n.up.railway.app

      # Порт самого приложения внутри контейнера
      - N8N_PORT=5555
      - PORT=5555

    ports:
      - "5555:5555"
    depends_on:
      - postgres
